In [1]:
import  torch

In [2]:
X = torch.arange(80).reshape(4, 2, 10).type(torch.float)
ln = torch.nn.LayerNorm(normalized_shape = X.shape[-1:], eps = 1e-12)
a = ln(X)

print(a[0, 1])

tensor([-1.5667, -1.2185, -0.8704, -0.5222, -0.1741,  0.1741,  0.5222,  0.8704,
         1.2185,  1.5667], grad_fn=<SelectBackward0>)


In [3]:
a.mean()

tensor(3.2783e-08, grad_fn=<MeanBackward0>)

In [4]:
from    galerkin_transformer    import  layers, model

Interactive environ: Jupyter themes not found.


In [10]:
from    torch       import  norm
from    torch.nn    import  Embedding


embed = Embedding(10, 6)
print(embed.weight)

sentences = torch.tensor([[0,1,2], [2,1,9]])
print(embed(sentences))

Parameter containing:
tensor([[ 1.0850,  0.2188, -0.5273,  1.3456,  1.0413, -0.1277],
        [-0.6997, -0.3943,  1.5471,  0.0903,  0.1757,  0.5586],
        [-1.0228,  1.6078,  0.2918, -1.3457, -0.3106,  0.8791],
        [ 0.7713, -0.0998,  0.5513,  0.0873,  0.2393,  0.8600],
        [ 0.3944, -2.1223,  0.2257,  0.6783, -0.8262,  0.3130],
        [ 0.1110,  0.2371,  0.3477,  0.1390,  1.4768, -0.7787],
        [ 1.6362, -0.3394, -0.4310, -0.5618, -0.2823, -0.5770],
        [-0.9098, -0.4526,  0.3027,  1.7093, -1.0119, -0.2089],
        [-1.0699,  1.6557,  2.1765, -1.3487, -0.6584, -0.5565],
        [ 0.2274,  1.3622,  0.6057, -0.7366, -1.0791, -0.8944]],
       requires_grad=True)
tensor([[[ 1.0850,  0.2188, -0.5273,  1.3456,  1.0413, -0.1277],
         [-0.6997, -0.3943,  1.5471,  0.0903,  0.1757,  0.5586],
         [-1.0228,  1.6078,  0.2918, -1.3457, -0.3106,  0.8791]],

        [[-1.0228,  1.6078,  0.2918, -1.3457, -0.3106,  0.8791],
         [-0.6997, -0.3943,  1.5471,  0.0903,  0

In [16]:
A = torch.arange(12*24).reshape(12, 24)
l = A.chunk(4, -1)
for t in l:
    print(t.shape)
    
    
    
    

torch.Size([12, 6])
torch.Size([12, 6])
torch.Size([12, 6])
torch.Size([12, 6])


In [ ]:
from    galerkin_transformer